### ISSUE TITLE
BW Flatpak desktop - blank window at launch

### ISSUE THREAD

**Issue by Leonov65** [bitwarden/clients#6757]
### Steps To Reproduce

After launching BW Flatpak the login window is blank. The box for master password entry does not appear. Hence I cannot login to my BW acct via the desktop app.
Menu bar at top of screen is present and functional. However some items are greyed out and hence unusable, eg account login options.
Problem persists after system restart.

Operating system:
Ubuntu 20.04 LTS.
BW desktop installed via Flatpak.
Flatpak version:
1.12.4-1flatpak1~20.04

### Expected Result

Window should render central box as normal to permit user account login.

### Actual Result

Cannot use Bitwarden desktop to access my account.
Browser plugins still working.

### Screenshots or Videos

![20231101-Bitwarden-blank-window-scnsht](https://github.com/bitwarden/clients/assets/68941417/a3fbcee8-05a1-4ee4-a79a-2c9afc5e50cd)
![20231102-Bitwarden-menu-items-grey-scnsht](https://github.com/bitwarden/clients/assets/68941417/31fc1c94-b694-41e2-a893-abc5face2b4d)

### Operating System

Linux

### Operating System Version

Ubuntu 20.04 LTS

### Installation method

Other

### Build Version

Version 2023.9.3 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ranisalt** [comment]
I have the same issue for a few days on Arch Linux. Here's an error log, it outputs a LOT of "Skia shader compilation error"

[bitwarden.log](https://github.com/bitwarden/clients/files/13232691/bitwarden.log)

**Comment by klaus4040** [comment]
Same, in the logs I say it fails with GL_NV Entensions, which makes sense since I have AMD ...  yet odd as to why it tries to use Nvidia stuff.
Found this: https://bbs.archlinux.org/viewtopic.php?id=285507
And starting it via

`flatpak run com.bitwarden.desktop --disable-gpu-driver-bug-workarounds`

indeed works

**Comment by Leonov65** [comment]
@klaus4040 
Thanks. That's a neat workaround.

Mine was to install BW via Snap. It gave a later version of BW:
Version 2023.10.0
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

**Comment by huaracheguarache** [comment]
Try to remove your GPU cache by running:

`rm -rf ~/.var/app/com.bitwarden.desktop/config/Bitwarden/Partitions/bitwarden/GPUCache`

That fixed the issue for me on Fedora 39 Silverblue.

**Comment by lucascaraca** [comment]
@huaracheguarache thanks! 
This also worked on Pop OS 22.04.

**Comment by alogcat** [comment]
Thank you @huaracheguarache , that worked on Nobara 38.

**Comment by Leonov65** [comment]
@huaracheguarache Your method works on Ubuntu 20.04 too.
Thank you.

**Comment by sammbw** [comment]
Hi there,

The flatpak is maintained by the community, not Bitwarden. You can use the [official .AppImage installer](https://bitwarden.com/download) from the Bitwarden website as an alternative while updates are pending for the flatpak application.

This issue will now be closed.

Thanks!

**Comment by Tater-K7S5A** [comment]
> Try to remove your GPU cache by running:
> 
> `rm -rf ~/.var/app/com.bitwarden.desktop/config/Bitwarden/Partitions/bitwarden/GPUCache`
> 
> That fixed the issue for me on Fedora 39 Silverblue.

Fixed for my Linux Mint 21.2 as well.  Thank you.
