### PR TITLE
[PM-40862][PM-40850] deps: Update Angular build toolchain and Storybook to clear advisories

### PR DESCRIPTION
**Pull request by BryanCunningham**
## 🎟️ Tracking

- [PM-40862](https://bitwarden.atlassian.net/browse/PM-40862) — vite dev-server advisories
- [PM-40850](https://bitwarden.atlassian.net/browse/PM-40850) — CVE-2026-55388, piscina 5.1.4 → 5.2.0

Supersedes #20842 (Renovate storybook monorepo bump, blocked on an ERESOLVE since July).

## 📔 Objective

Bump the Angular build toolchain to clear two sets of transitive dev-dependency advisories, and bump the Storybook monorepo so the fix needs no `overrides` workarounds.

### Advisories

Neither vite nor piscina is a direct dependency — `@angular/build` pins both exactly — so the fix is upgrading `@angular-devkit/build-angular` and `@angular/cli` from 21.2.9 to 21.2.24. Both stay within Angular 21; no framework or TypeScript change is required.

- **vite 7.3.2 → 7.3.6** (PM-40862) — clears GHSA-fx2h-pf6j-xcff (high, `server.fs.deny` bypass via Windows alternate paths) and GHSA-v6wh-96g9-6wx3 (launch-editor NTLMv2 hash disclosure).
- **piscina 5.1.4 → 5.2.0** (PM-40850) — clears CVE-2026-55388, prototype pollution gadget → RCE via an inherited `options.filename`.

The toolchain bump alone is not sufficient for vite. It gives `@angular/build` its own nested patched copy while the hoisted root copy stays at 7.3.2, because Storybook's `builder-vite` and `vite-tsconfig-paths` still accept it and npm will not re-resolve a satisfied range. That hoisted copy is the one the autofill lit Storybook loads — the only surface in the repo that actually runs vite — so vite is also constrained in `overrides` to dedupe the tree onto the patched version.

### Storybook 10.3.6 → 10.6.0

This started as the fix for a DEBT review finding on the `overrides` block, and turned out to need a real fix rather than a workaround. The esbuild constraints were unsatisfiable:

| Package | Field | Range | 0.28.1 OK? |
| --- | --- | --- | --- |
| `storybook@10.3.6` | dependencies | `^0.18.0 \|\| … \|\| ^0.27.0` | ❌ |
| `jest-preset-angular` | optionalDependencies | `>=0.28.0` | ✅ |
| `@angular/build@21.2.24` | dependencies | `0.28.1` (exact) | ✅ |
| `vite@7.3.6` | dependencies | `^0.27.0 \|\| ^0.28.0` | ✅ |

An `esbuild: "0.28.1"` override forced storybook outside its declared range. Dropping it wasn't free either — storybook's best in-range version is 0.27.7, which sits inside GHSA-g7r4-m6w7-qqqr (arbitrary file read via the dev server on Windows, fixed in 0.28.1).

**storybook 10.5.0 widened its esbuild range to include `^0.28.0`**, so bumping to 10.6.0 dissolves the conflict: one hoisted `esbuild@0.28.1` satisfies every consumer inside its own declared range, and **the esbuild override is deleted entirely**.

The bump requires declaring `@angular/platform-browser-dynamic` explicitly. `@storybook/angular` 10.5+ widened its peer on that package from `<22.0.0` to `<23.0.0`; nothing in this repo depends on it, so npm resolves the peer itself and picks 20.0.7, whose peers then collide with Angular 21.2.17. Pinning it to 21.2.17 alongside the rest of Angular resolves it. **This is the same ERESOLVE that has blocked Renovate from generating a lock file for #20842 since July.**

Also bumped in lockstep: `@storybook/addon-designs` → 11.1.4 (11.1.3 does not peer-accept storybook 10.6) and `eslint-plugin-storybook` → 10.6.0.

### The vite override is bounded, not pinned

`"vite": "^7.3.6"` rather than an exact pin. vite 8.3.0 is already the `latest` tag, and the only true *dependency* on vite is Angular's exact pin — every other consumer is an open **peer** (`*`, `^5 || ^6 || ^7 || ^8`). An unbounded floor such as `>=7.3.6` would resolve to 8.3.0 today and, since overrides outrank Angular's pin, put the builder on the rolldown-based major. The caret keeps the patched-version floor without reaching vite 8. It resolves to 7.3.6 today, so the lock file is unchanged for vite.

### Build script: explicit stats path for Chromatic

`build-storybook:ci` now passes `--webpack-stats-json=storybook-static` instead of the bare flag. The storybook bump broke Chromatic's TurboSnap on the Component Library build, and the cause is not visible from the diff: `@storybook/angular` reordered the type union on that builder option, from `["boolean","string"]` in 10.3.6 to `["string","boolean"]` in 10.6.0. Angular CLI parses a bare flag using the first type in the union, so `--webpack-stats-json` began yielding `""` rather than `true`. Storybook core gates on `options.webpackStatsJson || options.statsJson`; `""` is falsy, so it skipped writing the file with no error, and Chromatic failed with "Did not find preview-stats.json in your built Storybook."

Passing the directory explicitly restores it — verified locally, `Preview stats written to storybook-static/preview-stats.json`, matching the `storybookBuildDir` the workflow publishes from.

The autofill lit Storybook keeps the bare flag. It invokes the Storybook CLI directly rather than through Angular CLI, so it parses correctly, and it published successfully on the run where the CL build failed.

### Also

Prunes a stale nested `postcss@8.5.12` entry under `build-angular`. It was correct when 21.2.9 pinned that version, but 21.2.24 pins 8.5.23, and npm leaves the old entry behind and reports it as invalid.

`npm audit` findings drop from **87 to 72**.

## 📸 Screenshots

Not applicable — no UI surface is intentionally changed; this is a build-tooling dependency change.

**Chromatic has no green baseline on this branch.** It was *skipped* on the earlier commits here because the `paths-filter` gate did not match, so its first real run is on the Storybook bump. That run compares a 10.3.6 baseline against 10.6.0, so snapshot diffs are expected and need a human to review and accept them in the Chromatic UI — they are not evidence of a regression on their own.

[PM-40862]: https://bitwarden.atlassian.net/browse/PM-40862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PM-40850]: https://bitwarden.atlassian.net/browse/PM-40850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by vleague2 — DISMISSED** [review]

File: package.json [hunk 1]
```diff
@@ -242,7 +242,9 @@
     "@angular-devkit/build-angular": {
       "jest-environment-jsdom": "29.7.0"
     },
-    "tmp": ">=0.2.4"
+    "tmp": ">=0.2.4",
+    "vite": "7.3.6",
+    "esbuild": "0.28.1"
```
[the remark this answers is not in the document]
Comment (BryanCunningham) [reply package.json]: Good catch on both points — fixed in d471f9220d, though the investigation turned up two things worth recording.

**The esbuild pin was load-bearing after all.** Dropping it moves storybook to a nested `esbuild@0.27.7`, which is inside GHSA-g7r4-m6w7-qqqr (arbitrary file read via the dev server on Windows, fixed in 0.28.1) — `npm audit` went 73 → 74. storybook 10.3.6 caps esbuild at `^0.27.0` and the fix only exists in 0.28.1, so no layout satisfied both the declared range and the advisory. The override was a deliberate trade, not an oversight.

Resolved it properly instead: **storybook 10.5.0 widened its esbuild range to include `^0.28.0`**, so this now bumps the monorepo to 10.6.0. One hoisted `esbuild@0.28.1` satisfies every consumer inside its own declared range, and the override is deleted outright. That also required declaring `@angular/platform-browser-dynamic@21.2.17` — `@storybook/angular` 10.5+ widened its peer on it to `<23.0.0`, and with nothing in the repo depending on it npm picks 20.0.7 and collides with Angular 21. That is the same ERESOLVE that has blocked Renovate on #20842 since July.

**`>=7.3.6` would not be safe for vite.** vite 8.3.0 is already the `latest` tag, so `>=7.3.6` resolves to 8.3.0 — and since an override outranks `@angular/build`'s exact pin, it would put the Angular builder on vite 8 with no install error. vite 8 demotes esbuild to a peerDependency and drops rollup for rolldown; Angular pinning 7.3.6 exactly is the signal it hasn't validated that. The `tmp` precedent holds because `tmp` has no active major to drift into.

Used `"vite": "^7.3.6"` instead — same patched-version floor, follows Angular across 7.x, cannot reach vite 8. Resolves to 7.3.6 today, so the lock file is unchanged for vite. The holdback you describe then only bites at the 7→8 boundary, which is already a human `ng update` step (renovate.json5 disables majors for angular-cli).

`npm audit` is down to 72.

**Review by vleague2 — DISMISSED** [review]
Looks good, the lint fix will be needed so re-request me when that is done!

File: package.json [hunk 2]
```diff
@@ -50,10 +50,11 @@
     "libs/**/*"
   ],
   "devDependencies": {
-    "@angular-devkit/build-angular": "21.2.9",
+    "@angular-devkit/build-angular": "21.2.24",
     "@angular-eslint/schematics": "21.3.1",
-    "@angular/cli": "21.2.9",
+    "@angular/cli": "21.2.24",
     "@angular/compiler-cli": "21.2.17",
+    "@angular/platform-browser-dynamic": "21.2.17",
```
[the remark this answers is not in the document]
Comment (BryanCunningham) [reply package.json:58]: 🤖 Fixed — added to the UI Foundation block alongside the rest of the Angular and Storybook packages, which also gives Renovate the right reviewers for future bumps. `npm run lint:dep-ownership` now reports all dependencies owned. Committed locally, not yet pushed, so `Lint` will stay red here until it is.

On the other red checks, none are caused by this PR:

- **Run Nx Affected Tasks** — `state-test-utils:build` fails with `Cannot find name 'jest'`. Pre-existing on `main`: the identical four errors appear on #23337, where the check is *green* because `.github/workflows/nx.yml` sets `continue-on-error: true` on the nx step. `libs/state-test-utils/tsconfig.lib.json` sets `"types": ["node"]`, suppressing jest's ambient globals, while `src/fake-state.ts` uses `jest.fn` and `src/fake-state-provider.ts` imports `jest-mock-extended` (whose `lib/Mock.d.ts` references `jest.Mock` with no `reference types="jest"`); the sibling `tsconfig.spec.json` correctly uses `["jest", "node"]`. Broken since #15772, and never load-bearing — nothing consumes `dist/libs/state-test-utils`, since importers resolve through the `tsconfig.base.json` path mapping to source. Leaving it to Platform, who own that lib. This run is red only because the nx step was *cancelled*, and `continue-on-error` masks a failure but not a cancellation.
- **MacOS Beta Build** — flaky. Passed on `d471f9220d`, the commit carrying the whole lock file change, and failed on `d00fec8e30`, which changed only a build script string with no lock change.
- **Rust lint / Rust deny** — pre-existing, failing on every commit on this branch; `RUSTSEC-2026-0285`, and this PR touches no Cargo manifest.
- **Validate Linux … Snap** — flaky, `Unknown error: {}`.

**Review by vleague2 — APPROVED** [review]
